[tools]
go = "latest"
k9s = "latest"
python = "latest"
rust = "latest"
kubens = "latest"
kubectx = "latest"
kind = "latest"
kubectl = "latest"
aws-cli = "latest"
azure = "latest"
helm = "latest"
fzf = "latest"
opentofu = "latest"
flux2 = "latest"
kustomize = "latest"
uv = "latest"
lazydocker = "latest"
lazygit = "latest"
trivy = "latest"
neovim = "latest"
act = "latest"
localstack = "latest"

[settings]

[settings.python]
compile = false
